<a href="https://colab.research.google.com/github/biapeabody/Projeto_Final_Dados_03_10_ENEM_RR/blob/main/2_Notebooks_Colab/Enem2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importanto Bibliotecas

## **PROJETO FINAL - ENEM 2022**

## Estado de Roraima - RR

Thaís Falcão

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
caminho = '/content/drive/MyDrive/Projeto_Final/MICRODADOS_ENEM_2022.csv'


df = pd.read_csv(caminho, sep=';', encoding='latin1')

df.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210057943671,2022,14,M,2,2,1,1,2,1,...,B,A,A,A,A,A,A,A,A,A
1,210057516120,2022,14,M,2,1,1,1,16,1,...,E,E,B,E,B,B,E,B,E,B
2,210057280536,2022,5,F,1,2,1,1,2,1,...,A,A,A,A,A,A,C,A,A,B
3,210055724397,2022,6,M,1,3,1,1,2,1,...,B,A,A,C,A,A,C,B,B,B
4,210055097896,2022,4,M,0,3,1,1,1,1,...,A,A,A,A,A,A,B,A,A,A

In [ ]:
df.shape
# (linhas, colunas)

(3476105, 76)

In [ ]:
df.info()
# tipos de dados e se há valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3476105 entries, 0 to 3476104
Data columns (total 76 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_INSCRICAO            int64
 1   NU_ANO                  int64
 2   TP_FAIXA_ETARIA         int64
 3   TP_SEXO                 object
 4   TP_ESTADO_CIVIL         int64
 5   TP_COR_RACA             int64
 6   TP_NACIONALIDADE        int64
 7   TP_ST_CONCLUSAO         int64
 8   TP_ANO_CONCLUIU         int64
 9   TP_ESCOLA               int64
 10  TP_ENSINO               float64
 11  IN_TREINEIRO            int64
 12  CO_MUNICIPIO_ESC        float64
 13  NO_MUNICIPIO_ESC        object
 14  CO_UF_ESC               float64
 15  SG_UF_ESC               object
 16  TP_DEPENDENCIA_ADM_ESC  float64
 17  TP_LOCALIZACAO_ESC      float64
 18  TP_SIT_FUNC_ESC         float64
 19  CO_MUNICIPIO_PROVA      int64
 20  NO_MUNICIPIO_PROVA      object
 21  CO_UF_PROVA             int64
 22  SG_UF_PROVA             object
 23  TP_PRESENCA_CN          int64
 24  TP_PRESENCA_CH          int64
 25  TP_PRESENCA_LC          int64
 26  TP_PRESENCA_MT          int64
 27  CO_PROVA_CN             float64
 28  CO_PROVA_CH             float64
 29  CO_PROVA_LC             float64
 30  CO_PROVA_MT             float64
 31  NU_NOTA_CN              float64
 32  NU_NOTA_CH              float64
 33  NU_NOTA_LC              float64
 34  NU_NOTA_MT              float64
 35  TX_RESPOSTAS_CN         object
 36  TX_RESPOSTAS_CH         object
 37  TX_RESPOSTAS_LC         object
 38  TX_RESPOSTAS_MT         object
 39  TP_LINGUA               int64
 40  TX_GABARITO_CN          object
 41  TX_GABARITO_CH          object
 42  TX_GABARITO_LC          object
 43  TX_GABARITO_MT          object
 44  TP_STATUS_REDACAO       float64
 45  NU_NOTA_COMP1           float64
 46  NU_NOTA_COMP2           float64
 47  NU_NOTA_COMP3           float64
 48  NU_NOTA_COMP4           float64
 49  NU_NOTA_COMP5           float64
 50  NU_NOTA_REDACAO         float64
 51  Q001                    object
 52  Q002                    object
 53  Q003                    object
 54  Q004                    object
 55  Q005                    int64
 56  Q006                    object
 57  Q007                    object
 58  Q008                    object
 59  Q009                    object
 60  Q010                    object
 61  Q011                    object
 62  Q012                    object
 63  Q013                    object
 64  Q014                    object
 65  Q015                    object
 66  Q016                    object
 67  Q017                    object
 68  Q018                    object
 69  Q019                    object
 70  Q020                    object
 71  Q021                    object
 72  Q022                    object
 73  Q023                    object
 74  Q024                    object
 75  Q025                    object
dtypes: float64(21), int64(18), object(37)
memory usage: 2.0+ GB

In [ ]:
list(df.columns)
# listando as colunas - de forma organizada

['NU_INSCRICAO',
 'NU_ANO',
 'TP_FAIXA_ETARIA',
 'TP_SEXO',
 'TP_ESTADO_CIVIL',
 'TP_COR_RACA',
 'TP_NACIONALIDADE',
 'TP_ST_CONCLUSAO',
 'TP_ANO_CONCLUIU',
 'TP_ESCOLA',
 'TP_ENSINO',
 'IN_TREINEIRO',
 'CO_MUNICIPIO_ESC',
 'NO_MUNICIPIO_ESC',
 'CO_UF_ESC',
 'SG_UF_ESC',
 'TP_DEPENDENCIA_ADM_ESC',
 'TP_LOCALIZACAO_ESC',
 'TP_SIT_FUNC_ESC',
 'CO_MUNICIPIO_PROVA',
 'NO_MUNICIPIO_PROVA',
 'CO_UF_PROVA',
 'SG_UF_PROVA',
 'TP_PRESENCA_CN',
 'TP_PRESENCA_CH',
 'TP_PRESENCA_LC',
 'TP_PRESENCA_MT',
 'CO_PROVA_CN',
 'CO_PROVA_CH',
 'CO_PROVA_LC',
 'CO_PROVA_MT',
 'NU_NOTA_CN',
 'NU_NOTA_CH',
 'NU_NOTA_LC',
 'NU_NOTA_MT',
 'TX_RESPOSTAS_CN',
 'TX_RESPOSTAS_CH',
 'TX_RESPOSTAS_LC',
 'TX_RESPOSTAS_MT',
 'TP_LINGUA',
 'TX_GABARITO_CN',
 'TX_GABARITO_CH',
 'TX_GABARITO_LC',
 'TX_GABARITO_MT',
 'TP_STATUS_REDACAO',
 'NU_NOTA_COMP1',
 'NU_NOTA_COMP2',
 'NU_NOTA_COMP3',
 'NU_NOTA_COMP4',
 'NU_NOTA_COMP5',
 'NU_NOTA_REDACAO',
 'Q001',
 'Q002',
 'Q003',
 'Q004',
 'Q005',
 'Q006',
 'Q007',
 'Q008',
 'Q009',
 'Q010',
 'Q011',
 'Q012',
 'Q013',
 'Q014',
 'Q015',
 'Q016',
 'Q017',
 'Q018',
 'Q019',
 'Q020',
 'Q021',
 'Q022',
 'Q023',
 'Q024',
 'Q025']

In [ ]:
# Filtrar apenas os registros de Roraima (SG_UF_PROVA == 'RR')
df_limpo = df[df['SG_UF_PROVA'] == 'RR']

In [ ]:
df_limpo['SG_UF_PROVA'].value_counts()

SG_UF_PROVA
RR    8434
Name: count, dtype: int64

In [ ]:
# lista das colunas que vão ficar, as demais vão ser dropadas

colunas_desejadas = [
    'NU_INSCRICAO',
    'NU_ANO',
    'TP_FAIXA_ETARIA',
    'TP_SEXO',
    'TP_ESTADO_CIVIL',
    'TP_COR_RACA',
    'TP_NACIONALIDADE',
    'TP_ESCOLA',
    'TP_ENSINO',
    'IN_TREINEIRO',
    'NO_MUNICIPIO_PROVA',
    'SG_UF_PROVA',
    'TP_DEPENDENCIA_ADM_ESC',
    'TP_LOCALIZACAO_ESC'
]

df_limpo = df_limpo[colunas_desejadas]

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
971,210054682066,2022,9,F,2,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1173,210054853157,2022,3,F,1,3,1,2,1.0,0,Boa Vista,RR,1.0,1.0
1188,210054992996,2022,4,F,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1292,210056752789,2022,6,M,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1503,210055459465,2022,10,F,2,1,1,1,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# Dicionário de mapeamento
faixa_etaria_map = {
    1: "Menor de 17 anos",
    2: "17 anos",
    3: "18 anos",
    4: "19 anos",
    5: "20 anos",
    6: "21 anos",
    7: "22 anos",
    8: "23 anos",
    9: "24 anos",
    10: "25 anos",
    11: "Entre 26 e 30 anos",
    12: "Entre 31 e 35 anos",
    13: "Entre 36 e 40 anos",
    14: "Entre 41 e 45 anos",
    15: "Entre 46 e 50 anos",
    16: "Entre 51 e 55 anos",
    17: "Entre 56 e 60 anos",
    18: "Entre 61 e 65 anos",
    19: "Entre 66 e 70 anos",
    20: "Maior de 70 anos"
}

# substituir categoria pela descrição
df_limpo['TP_FAIXA_ETARIA'] = df_limpo['TP_FAIXA_ETARIA'].map(faixa_etaria_map)

df_limpo[['TP_FAIXA_ETARIA']].head()

     TP_FAIXA_ETARIA
971          24 anos
1173         18 anos
1188         19 anos
1292         21 anos
1503         25 anos

In [ ]:
# dic de mapeamento
mapeamento_estado_civil = {
    0: "Não informado",
    1: "Solteiro(a)",
    2: "Casado(a)/Mora com companheiro(a)",
    3: "Divorciado(a)/Desquitado(a)/Separado(a)",
    4: "Viúvo(a)"
}


df_limpo['TP_ESTADO_CIVIL'] = df_limpo['TP_ESTADO_CIVIL'].map(mapeamento_estado_civil)

In [ ]:
# dicionário de mapeamento
mapeamento_cor = {
    0: "Não declarado",
    1: "Branca",
    2: "Preta",
    3: "Parda",
    4: "Amarela",
    5: "Indígena",
    6: "Não dispõe da informação"
}

# substituição
df_limpo['TP_COR_RACA'] = df_limpo['TP_COR_RACA'].map(mapeamento_cor)

df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            5068
Branca           1979
Preta             638
Indígena          486
Não declarado     164
Amarela            99
Name: count, dtype: int64

In [ ]:
df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            5068
Branca           1979
Preta             638
Indígena          486
Não declarado     164
Amarela            99
Name: count, dtype: int64

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
971,210054682066,2022,24 anos,F,Casado(a)/Mora com companheiro(a),Parda,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1173,210054853157,2022,18 anos,F,Solteiro(a),Parda,1,2,1.0,0,Boa Vista,RR,1.0,1.0
1188,210054992996,2022,19 anos,F,Solteiro(a),Parda,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1292,210056752789,2022,21 anos,M,Solteiro(a),Parda,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1503,210055459465,2022,25 anos,F,Casado(a)/Mora com companheiro(a),Branca,1,1,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# dicionário de mapeamento
mapeamento_nacionalidade = {
    0: "Não informado",
    1: "Brasileiro(a)",
    2: "Brasileiro(a) Naturalizado(a)",
    3: "Estrangeiro(a)",
    4: "Brasileiro(a) Nato(a), nascido(a) no exterior"
}

# substituição
df_limpo['TP_NACIONALIDADE'] = df_limpo['TP_NACIONALIDADE'].map(mapeamento_nacionalidade)

In [ ]:
# dicionário de mapeamento
mapeamento_escola = {
    1: 'Não Respondeu',
    2: 'Pública',
    3: 'Privada'
}

# Substituir os valores numéricos pelos textos
df_limpo['TP_ESCOLA'] = df_limpo['TP_ESCOLA'].map(mapeamento_escola)

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_ESCOLA'].value_counts())

TP_ESCOLA
Não Respondeu    5500
Pública          2698
Privada           236
Name: count, dtype: int64

In [ ]:
df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            5068
Branca           1979
Preta             638
Indígena          486
Não declarado     164
Amarela            99
Name: count, dtype: int64

In [ ]:
mapeamento_dependencia = {
    1: 'Federal',
    2: 'Estadual',
    3: 'Municipal',
    4: 'Privada'
}

df_limpo['TP_DEPENDENCIA_ADM_ESC'] = df_limpo['TP_DEPENDENCIA_ADM_ESC'].map(mapeamento_dependencia)

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_DEPENDENCIA_ADM_ESC'].value_counts())

TP_DEPENDENCIA_ADM_ESC
Estadual     1698
Federal       262
Privada       258
Municipal       3
Name: count, dtype: int64

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
971,210054682066,2022,24 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
1173,210054853157,2022,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Pública,1.0,0,Boa Vista,RR,Federal,1.0
1188,210054992996,2022,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
1292,210056752789,2022,21 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
1503,210055459465,2022,25 anos,F,Casado(a)/Mora com companheiro(a),Branca,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# mapeamento TP_ENSINO
mapeamento_ensino = {
    1: "Ensino Regular",
    2: "Educação Especial - Modalidade Substitutiva"
}

df_limpo['TP_ENSINO'] = df_limpo['TP_ENSINO'].map(mapeamento_ensino)



# mapeamento IN_TREINEIRO
mapeamento_treineiro = {
    1: "Sim",
    0: "Não"
}

df_limpo['IN_TREINEIRO'] = df_limpo['IN_TREINEIRO'].map(mapeamento_treineiro)

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_ENSINO'].value_counts())
print(df_limpo['IN_TREINEIRO'].value_counts())

TP_ENSINO
Ensino Regular                                 2760
Educação Especial - Modalidade Substitutiva      14
Name: count, dtype: int64
IN_TREINEIRO
Não    7163
Sim    1271
Name: count, dtype: int64

In [ ]:
mapa_localizacao = {
    1: 'Urbana',
    2: 'Rural'
}

df_limpo['TP_LOCALIZACAO_ESC'] = df_limpo['TP_LOCALIZACAO_ESC'].map(mapa_localizacao)

In [ ]:
print(df_limpo['TP_LOCALIZACAO_ESC'].value_counts())

TP_LOCALIZACAO_ESC
Urbana    2033
Rural      188
Name: count, dtype: int64

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_LOCALIZACAO_ESC'].value_counts())

TP_LOCALIZACAO_ESC
Urbana    2033
Rural      188
Name: count, dtype: int64

In [ ]:
print(df_limpo['TP_DEPENDENCIA_ADM_ESC'].value_counts())

TP_DEPENDENCIA_ADM_ESC
Estadual     1698
Federal       262
Privada       258
Municipal       3
Name: count, dtype: int64

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
971,210054682066,2022,24 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1173,210054853157,2022,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Pública,Ensino Regular,Não,Boa Vista,RR,Federal,Urbana
1188,210054992996,2022,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1292,210056752789,2022,21 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1503,210055459465,2022,25 anos,F,Casado(a)/Mora com companheiro(a),Branca,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN

In [ ]:
df_limpo.shape
# (linhas, colunas)

(8434, 14)

In [ ]:
# Dicionário de renomeação
novos_nomes = {
    'NU_INSCRICAO': 'inscricao',
    'NU_ANO': 'ano',
    'TP_FAIXA_ETARIA': 'faixa_etaria',
    'TP_SEXO': 'sexo',
    'TP_ESTADO_CIVIL': 'estado_civil',
    'TP_COR_RACA': 'cor_raca',
    'TP_NACIONALIDADE': 'nacionalidade',
    'TP_ESCOLA': 'tipo_escola',
    'TP_ENSINO': 'tipo_ensino',
    'IN_TREINEIRO': 'treineiro',
    'NO_MUNICIPIO_PROVA': 'municipio_prova',
    'SG_UF_PROVA': 'uf_prova',
    'TP_DEPENDENCIA_ADM_ESC': 'dependencia_adm_escola',
    'TP_LOCALIZACAO_ESC': 'localizacao_escola'
}

# nova variavel para novo dataset
# df → df_limpo → df_limpo_rr
df_limpo_rr = df_limpo.rename(columns=novos_nomes)

# ver as novas colunas
df_limpo_rr.columns

Index(['inscricao', 'ano', 'faixa_etaria', 'sexo', 'estado_civil', 'cor_raca',
       'nacionalidade', 'tipo_escola', 'tipo_ensino', 'treineiro',
       'municipio_prova', 'uf_prova', 'dependencia_adm_escola',
       'localizacao_escola'],
      dtype='object')

In [ ]:
df_limpo_rr.head()

,inscricao,ano,faixa_etaria,sexo,estado_civil,cor_raca,nacionalidade,tipo_escola,tipo_ensino,treineiro,municipio_prova,uf_prova,dependencia_adm_escola,localizacao_escola
971,210054682066,2022,24 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1173,210054853157,2022,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Pública,Ensino Regular,Não,Boa Vista,RR,Federal,Urbana
1188,210054992996,2022,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1292,210056752789,2022,21 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1503,210055459465,2022,25 anos,F,Casado(a)/Mora com companheiro(a),Branca,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN

In [ ]:
df_limpo_rr['tipo_ensino'].value_counts()

tipo_ensino
Ensino Regular                                 2760
Educação Especial - Modalidade Substitutiva      14
Name: count, dtype: int64

In [ ]:
df_limpo_rr['dependencia_adm_escola'].value_counts()

dependencia_adm_escola
Estadual     1698
Federal       262
Privada       258
Municipal       3
Name: count, dtype: int64

In [ ]:
df_limpo_rr['localizacao_escola'].value_counts()

localizacao_escola
Urbana    2033
Rural      188
Name: count, dtype: int64

In [ ]:
### **Base de Dados Limpa - Salvamento**

In [ ]:
pasta_destino = '/content/drive/MyDrive/Projeto_Final'

# nome do arquivo limpo
arquivo_destino = pasta_destino + '/enem2022_rr_limpo.csv'

df_limpo_rr.to_csv(arquivo_destino, index=False, sep=';', encoding='utf-8')

print(f"Arquivo salvo em: {arquivo_destino}")

Arquivo salvo em: /content/drive/MyDrive/Projeto_Final/enem2022_rr_limpo.csv