<a href="https://colab.research.google.com/github/biapeabody/Projeto_Final_Dados_03_10_ENEM_RR/blob/main/2_Notebooks_Colab/Enem2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Bibliotecas**

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

### **Conexão com o Google Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **Base de Dados - ENEM 2023**

In [ ]:
caminho = '/content/drive/MyDrive/Projeto Final - DADOS_3_10/1. Bases de Dados/Dados_2023/MICRODADOS_ENEM_2023.csv'

df = pd.read_csv(caminho, sep=';', encoding='latin1')

df.head()

In [ ]:
df.shape
# (linhas, colunas)

(3933955, 76)

In [ ]:
df.info()
# tipos de dados e se há valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3933955 entries, 0 to 3933954
Data columns (total 76 columns):
 #   Column                  Dtype
---  ------                  -----
 0   NU_INSCRICAO            int64
 1   NU_ANO                  int64
 2   TP_FAIXA_ETARIA         int64
 3   TP_SEXO                 object
 4   TP_ESTADO_CIVIL         int64
 5   TP_COR_RACA             int64
 6   TP_NACIONALIDADE        int64
 7   TP_ST_CONCLUSAO         int64
 8   TP_ANO_CONCLUIU         int64
 9   TP_ESCOLA               int64
 10  TP_ENSINO               float64
 11  IN_TREINEIRO            int64
 12  CO_MUNICIPIO_ESC        float64
 13  NO_MUNICIPIO_ESC        object
 14  CO_UF_ESC               float64
 15  SG_UF_ESC               object
 16  TP_DEPENDENCIA_ADM_ESC  float64
 17  TP_LOCALIZACAO_ESC      float64
 18  TP_SIT_FUNC_ESC         float64
 19  CO_MUNICIPIO_PROVA      int64
 20  NO_MUNICIPIO_PROVA      object
 21  CO_UF_PROVA             int64
 22  SG_UF_PROVA             object
 23  TP_PRESENCA_CN          int64
 24  TP_PRESENCA_CH          int64
 25  TP_PRESENCA_LC          int64
 26  TP_PRESENCA_MT          int64
 27  CO_PROVA_CN             float64
 28  CO_PROVA_CH             float64
 29  CO_PROVA_LC             float64
 30  CO_PROVA_MT             float64
 31  NU_NOTA_CN              float64
 32  NU_NOTA_CH              float64
 33  NU_NOTA_LC              float64
 34  NU_NOTA_MT              float64
 35  TX_RESPOSTAS_CN         object
 36  TX_RESPOSTAS_CH         object
 37  TX_RESPOSTAS_LC         object
 38  TX_RESPOSTAS_MT         object
 39  TP_LINGUA               int64
 40  TX_GABARITO_CN          object
 41  TX_GABARITO_CH          object
 42  TX_GABARITO_LC          object
 43  TX_GABARITO_MT          object
 44  TP_STATUS_REDACAO       float64
 45  NU_NOTA_COMP1           float64
 46  NU_NOTA_COMP2           float64
 47  NU_NOTA_COMP3           float64
 48  NU_NOTA_COMP4           float64
 49  NU_NOTA_COMP5           float64
 50  NU_NOTA_REDACAO         float64
 51  Q001                    object
 52  Q002                    object
 53  Q003                    object
 54  Q004                    object
 55  Q005                    int64
 56  Q006                    object
 57  Q007                    object
 58  Q008                    object
 59  Q009                    object
 60  Q010                    object
 61  Q011                    object
 62  Q012                    object
 63  Q013                    object
 64  Q014                    object
 65  Q015                    object
 66  Q016                    object
 67  Q017                    object
 68  Q018                    object
 69  Q019                    object
 70  Q020                    object
 71  Q021                    object
 72  Q022                    object
 73  Q023                    object
 74  Q024                    object
 75  Q025                    object
dtypes: float64(21), int64(18), object(37)
memory usage: 2.2+ GB

In [ ]:
list(df.columns)
# listando as colunas - de forma organizada

['NU_INSCRICAO',
 'NU_ANO',
 'TP_FAIXA_ETARIA',
 'TP_SEXO',
 'TP_ESTADO_CIVIL',
 'TP_COR_RACA',
 'TP_NACIONALIDADE',
 'TP_ST_CONCLUSAO',
 'TP_ANO_CONCLUIU',
 'TP_ESCOLA',
 'TP_ENSINO',
 'IN_TREINEIRO',
 'CO_MUNICIPIO_ESC',
 'NO_MUNICIPIO_ESC',
 'CO_UF_ESC',
 'SG_UF_ESC',
 'TP_DEPENDENCIA_ADM_ESC',
 'TP_LOCALIZACAO_ESC',
 'TP_SIT_FUNC_ESC',
 'CO_MUNICIPIO_PROVA',
 'NO_MUNICIPIO_PROVA',
 'CO_UF_PROVA',
 'SG_UF_PROVA',
 'TP_PRESENCA_CN',
 'TP_PRESENCA_CH',
 'TP_PRESENCA_LC',
 'TP_PRESENCA_MT',
 'CO_PROVA_CN',
 'CO_PROVA_CH',
 'CO_PROVA_LC',
 'CO_PROVA_MT',
 'NU_NOTA_CN',
 'NU_NOTA_CH',
 'NU_NOTA_LC',
 'NU_NOTA_MT',
 'TX_RESPOSTAS_CN',
 'TX_RESPOSTAS_CH',
 'TX_RESPOSTAS_LC',
 'TX_RESPOSTAS_MT',
 'TP_LINGUA',
 'TX_GABARITO_CN',
 'TX_GABARITO_CH',
 'TX_GABARITO_LC',
 'TX_GABARITO_MT',
 'TP_STATUS_REDACAO',
 'NU_NOTA_COMP1',
 'NU_NOTA_COMP2',
 'NU_NOTA_COMP3',
 'NU_NOTA_COMP4',
 'NU_NOTA_COMP5',
 'NU_NOTA_REDACAO',
 'Q001',
 'Q002',
 'Q003',
 'Q004',
 'Q005',
 'Q006',
 'Q007',
 'Q008',
 'Q009',
 'Q010',
 'Q011',
 'Q012',
 'Q013',
 'Q014',
 'Q015',
 'Q016',
 'Q017',
 'Q018',
 'Q019',
 'Q020',
 'Q021',
 'Q022',
 'Q023',
 'Q024',
 'Q025']

In [ ]:
# Filtrar apenas os registros de Roraima (SG_UF_PROVA == 'RR')
df_limpo = df[df['SG_UF_PROVA'] == 'RR']

In [ ]:
df_limpo['SG_UF_PROVA'].value_counts()

SG_UF_PROVA
RR    9639
Name: count, dtype: int64

In [ ]:
# lista das colunas que vão ficar, as demais vão ser dropadas (mesmas colunas de 2024)
# em 2024 fiz dic de colunas para remover, aqui fiz o inverso (mais fácil) para não errar

colunas_desejadas = [
    'NU_INSCRICAO',
    'NU_ANO',
    'TP_FAIXA_ETARIA',
    'TP_SEXO',
    'TP_ESTADO_CIVIL',
    'TP_COR_RACA',
    'TP_NACIONALIDADE',
    'TP_ESCOLA',
    'TP_ENSINO',
    'IN_TREINEIRO',
    'NO_MUNICIPIO_PROVA',
    'SG_UF_PROVA',
    'TP_DEPENDENCIA_ADM_ESC',
    'TP_LOCALIZACAO_ESC'
]

df_limpo = df_limpo[colunas_desejadas]

## **Base de Dados - Transformação**

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
692,210059589809,2023,14,M,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
762,210058073317,2023,4,F,1,1,1,1,NaN,0,Boa Vista,RR,NaN,NaN
778,210059868174,2023,14,M,2,3,1,1,NaN,0,Mucajaí,RR,NaN,NaN
1333,210058969698,2023,7,F,1,3,1,1,NaN,0,Alto Alegre,RR,NaN,NaN
2043,210058405079,2023,4,F,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# Dicionário de mapeamento
faixa_etaria_map = {
    1: "Menor de 17 anos",
    2: "17 anos",
    3: "18 anos",
    4: "19 anos",
    5: "20 anos",
    6: "21 anos",
    7: "22 anos",
    8: "23 anos",
    9: "24 anos",
    10: "25 anos",
    11: "Entre 26 e 30 anos",
    12: "Entre 31 e 35 anos",
    13: "Entre 36 e 40 anos",
    14: "Entre 41 e 45 anos",
    15: "Entre 46 e 50 anos",
    16: "Entre 51 e 55 anos",
    17: "Entre 56 e 60 anos",
    18: "Entre 61 e 65 anos",
    19: "Entre 66 e 70 anos",
    20: "Maior de 70 anos"
}

# substituir categoria pela descrição
df_limpo['TP_FAIXA_ETARIA'] = df_limpo['TP_FAIXA_ETARIA'].map(faixa_etaria_map)

df_limpo[['TP_FAIXA_ETARIA']].head()

         TP_FAIXA_ETARIA
692   Entre 41 e 45 anos
762              19 anos
778   Entre 41 e 45 anos
1333             22 anos
2043             19 anos

In [ ]:
# dic de mapeamento
mapeamento_estado_civil = {
    0: "Não informado",
    1: "Solteiro(a)",
    2: "Casado(a)/Mora com companheiro(a)",
    3: "Divorciado(a)/Desquitado(a)/Separado(a)",
    4: "Viúvo(a)"
}


df_limpo['TP_ESTADO_CIVIL'] = df_limpo['TP_ESTADO_CIVIL'].map(mapeamento_estado_civil)

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
692,210059589809,2023,Entre 41 e 45 anos,M,Solteiro(a),3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
762,210058073317,2023,19 anos,F,Solteiro(a),1,1,1,NaN,0,Boa Vista,RR,NaN,NaN
778,210059868174,2023,Entre 41 e 45 anos,M,Casado(a)/Mora com companheiro(a),3,1,1,NaN,0,Mucajaí,RR,NaN,NaN
1333,210058969698,2023,22 anos,F,Solteiro(a),3,1,1,NaN,0,Alto Alegre,RR,NaN,NaN
2043,210058405079,2023,19 anos,F,Solteiro(a),3,1,1,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# dicionário de mapeamento
mapeamento_cor = {
    0: "Não declarado",
    1: "Branca",
    2: "Preta",
    3: "Parda",
    4: "Amarela",
    5: "Indígena",
    6: "Não dispõe da informação"
}

# substituição
df_limpo['TP_COR_RACA'] = df_limpo['TP_COR_RACA'].map(mapeamento_cor)

df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            5672
Branca           2321
Preta             805
Indígena          598
Não declarado     135
Amarela           108
Name: count, dtype: int64

In [ ]:
df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            5672
Branca           2321
Preta             805
Indígena          598
Não declarado     135
Amarela           108
Name: count, dtype: int64

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
692,210059589809,2023,Entre 41 e 45 anos,M,Solteiro(a),Parda,1,1,NaN,0,Boa Vista,RR,NaN,NaN
762,210058073317,2023,19 anos,F,Solteiro(a),Branca,1,1,NaN,0,Boa Vista,RR,NaN,NaN
778,210059868174,2023,Entre 41 e 45 anos,M,Casado(a)/Mora com companheiro(a),Parda,1,1,NaN,0,Mucajaí,RR,NaN,NaN
1333,210058969698,2023,22 anos,F,Solteiro(a),Parda,1,1,NaN,0,Alto Alegre,RR,NaN,NaN
2043,210058405079,2023,19 anos,F,Solteiro(a),Parda,1,1,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# dicionário de mapeamento
mapeamento_nacionalidade = {
    0: "Não informado",
    1: "Brasileiro(a)",
    2: "Brasileiro(a) Naturalizado(a)",
    3: "Estrangeiro(a)",
    4: "Brasileiro(a) Nato(a), nascido(a) no exterior"
}

# substituição
df_limpo['TP_NACIONALIDADE'] = df_limpo['TP_NACIONALIDADE'].map(mapeamento_nacionalidade)

In [ ]:
# dicionário de mapeamento
mapeamento_escola = {
    1: 'Não Respondeu',
    2: 'Pública',
    3: 'Privada'
}

# Substituir os valores numéricos pelos textos
df_limpo['TP_ESCOLA'] = df_limpo['TP_ESCOLA'].map(mapeamento_escola)

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_ESCOLA'].value_counts())

TP_ESCOLA
Não Respondeu    6425
Pública          2919
Privada           295
Name: count, dtype: int64

In [ ]:
df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            5672
Branca           2321
Preta             805
Indígena          598
Não declarado     135
Amarela           108
Name: count, dtype: int64

In [ ]:
mapeamento_dependencia = {
    1: 'Federal',
    2: 'Estadual',
    3: 'Municipal',
    4: 'Privada'
}

df_limpo['TP_DEPENDENCIA_ADM_ESC'] = df_limpo['TP_DEPENDENCIA_ADM_ESC'].map(mapeamento_dependencia)

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_DEPENDENCIA_ADM_ESC'].value_counts())

TP_DEPENDENCIA_ADM_ESC
Estadual     1646
Federal       324
Privada       309
Municipal       4
Name: count, dtype: int64

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
692,210059589809,2023,Entre 41 e 45 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
762,210058073317,2023,19 anos,F,Solteiro(a),Branca,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
778,210059868174,2023,Entre 41 e 45 anos,M,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Mucajaí,RR,NaN,NaN
1333,210058969698,2023,22 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Alto Alegre,RR,NaN,NaN
2043,210058405079,2023,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# mapeamento TP_ENSINO
mapeamento_ensino = {
    1: "Ensino Regular",
    2: "Educação Especial - Modalidade Substitutiva"
}

df_limpo['TP_ENSINO'] = df_limpo['TP_ENSINO'].map(mapeamento_ensino)



# mapeamento IN_TREINEIRO
mapeamento_treineiro = {
    1: "Sim",
    0: "Não"
}

df_limpo['IN_TREINEIRO'] = df_limpo['IN_TREINEIRO'].map(mapeamento_treineiro)

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_ENSINO'].value_counts())
print(df_limpo['IN_TREINEIRO'].value_counts())

TP_ENSINO
Ensino Regular                                 3074
Educação Especial - Modalidade Substitutiva      15
Name: count, dtype: int64
IN_TREINEIRO
Não    7972
Sim    1667
Name: count, dtype: int64

In [ ]:
mapa_localizacao = {
    1: 'Urbana',
    2: 'Rural'
}

df_limpo['TP_LOCALIZACAO_ESC'] = df_limpo['TP_LOCALIZACAO_ESC'].map(mapa_localizacao)

In [ ]:
print(df_limpo['TP_LOCALIZACAO_ESC'].value_counts())

TP_LOCALIZACAO_ESC
Urbana    2063
Rural      220
Name: count, dtype: int64

In [ ]:
# distribuição de cada coluna
print(df_limpo['TP_LOCALIZACAO_ESC'].value_counts())

TP_LOCALIZACAO_ESC
Urbana    2063
Rural      220
Name: count, dtype: int64

In [ ]:
print(df_limpo['TP_DEPENDENCIA_ADM_ESC'].value_counts())

TP_DEPENDENCIA_ADM_ESC
Estadual     1646
Federal       324
Privada       309
Municipal       4
Name: count, dtype: int64

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
692,210059589809,2023,Entre 41 e 45 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
762,210058073317,2023,19 anos,F,Solteiro(a),Branca,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
778,210059868174,2023,Entre 41 e 45 anos,M,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Mucajaí,RR,NaN,NaN
1333,210058969698,2023,22 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Alto Alegre,RR,NaN,NaN
2043,210058405079,2023,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN

In [ ]:
df_limpo.shape
# (linhas, colunas)

(9639, 14)

In [ ]:
# Dicionário de renomeação
novos_nomes = {
    'NU_INSCRICAO': 'inscricao',
    'NU_ANO': 'ano',
    'TP_FAIXA_ETARIA': 'faixa_etaria',
    'TP_SEXO': 'sexo',
    'TP_ESTADO_CIVIL': 'estado_civil',
    'TP_COR_RACA': 'cor_raca',
    'TP_NACIONALIDADE': 'nacionalidade',
    'TP_ESCOLA': 'tipo_escola',
    'TP_ENSINO': 'tipo_ensino',
    'IN_TREINEIRO': 'treineiro',
    'NO_MUNICIPIO_PROVA': 'municipio_prova',
    'SG_UF_PROVA': 'uf_prova',
    'TP_DEPENDENCIA_ADM_ESC': 'dependencia_adm_escola',
    'TP_LOCALIZACAO_ESC': 'localizacao_escola'
}

# nova variavel para novo dataset
# df → df_limpo → df_limpo_rr
df_limpo_rr = df_limpo.rename(columns=novos_nomes)

# ver as novas colunas
df_limpo_rr.columns

Index(['inscricao', 'ano', 'faixa_etaria', 'sexo', 'estado_civil', 'cor_raca',
       'nacionalidade', 'tipo_escola', 'tipo_ensino', 'treineiro',
       'municipio_prova', 'uf_prova', 'dependencia_adm_escola',
       'localizacao_escola'],
      dtype='object')

In [ ]:
df_limpo_rr.head()

,inscricao,ano,faixa_etaria,sexo,estado_civil,cor_raca,nacionalidade,tipo_escola,tipo_ensino,treineiro,municipio_prova,uf_prova,dependencia_adm_escola,localizacao_escola
692,210059589809,2023,Entre 41 e 45 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
762,210058073317,2023,19 anos,F,Solteiro(a),Branca,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
778,210059868174,2023,Entre 41 e 45 anos,M,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Mucajaí,RR,NaN,NaN
1333,210058969698,2023,22 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Alto Alegre,RR,NaN,NaN
2043,210058405079,2023,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN

In [ ]:
df_limpo_rr['tipo_ensino'].value_counts()

tipo_ensino
Ensino Regular                                 3074
Educação Especial - Modalidade Substitutiva      15
Name: count, dtype: int64

In [ ]:
df_limpo_rr['dependencia_adm_escola'].value_counts()

dependencia_adm_escola
Estadual     1646
Federal       324
Privada       309
Municipal       4
Name: count, dtype: int64

In [ ]:
df_limpo_rr['localizacao_escola'].value_counts()

localizacao_escola
Urbana    2063
Rural      220
Name: count, dtype: int64

### **Base de Dados Limpa - Salvamento**

In [ ]:
pasta_destino = '/content/drive/MyDrive/Projeto Final - DADOS_3_10/3. Bases de Dados Limpas'

# nome do arquivo .csv lá na pasta destino
arquivo_destino = pasta_destino + '/enem2023_rr_limpo.csv'

# df_limpo_rr vai ser salvo em .cvs
df_limpo_rr.to_csv(arquivo_destino, index=False, sep=';', encoding='utf-8')

print(f"Arquivo salvo em: {arquivo_destino}")

Arquivo salvo em: /content/drive/MyDrive/Projeto Final - DADOS_3_10/3. Bases de Dados Limpas/enem2023_rr_limpo.csv