<a href="https://colab.research.google.com/github/biapeabody/Projeto_Final_Dados_03_10_ENEM_RR/blob/main/2_Notebooks_Colab/Enem2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
caminho = '/content/drive/MyDrive/Projeto Final - DADOS_3_10/1. Bases de Dados/Dados_2020/ENEM_2020_RR.csv'

df = pd.read_csv(caminho, sep=';', encoding='latin1')

df.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA
0,200006271946,2020,11,F,1,2,1,1,11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1501402,Belém,15,PA
1,200001195856,2020,11,M,2,3,1,1,11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,2408102,Natal,24,RN
2,200001943954,2020,4,F,2,3,2,2,0,2,...,Salvador,29.0,BA,2.0,1.0,1.0,2927408,Salvador,29,BA
3,200001908998,2020,2,M,1,3,1,2,0,2,...,Santana de Parnaíba,35.0,SP,3.0,1.0,1.0,3547304,Santana de Parnaíba,35,SP
4,200001634757,2020,4,F,1,3,2,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,3121605,Diamantina,31,MG

In [ ]:
df.shape
# (linhas, colunas)

(1048575, 23)

In [ ]:
df.info()
# tipos de dados e se há valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 23 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   NU_INSCRICAO            1048575 non-null  int64
 1   NU_ANO                  1048575 non-null  int64
 2   TP_FAIXA_ETARIA         1048575 non-null  int64
 3   TP_SEXO                 1048575 non-null  object
 4   TP_ESTADO_CIVIL         1048575 non-null  int64
 5   TP_COR_RACA             1048575 non-null  int64
 6   TP_NACIONALIDADE        1048575 non-null  int64
 7   TP_ST_CONCLUSAO         1048575 non-null  int64
 8   TP_ANO_CONCLUIU         1048575 non-null  int64
 9   TP_ESCOLA               1048575 non-null  int64
 10  TP_ENSINO               356881 non-null   float64
 11  IN_TREINEIRO            1048575 non-null  int64
 12  CO_MUNICIPIO_ESC        225748 non-null   float64
 13  NO_MUNICIPIO_ESC        225748 non-null   object
 14  CO_UF_ESC               225748 non-null   float64
 15  SG_UF_ESC               225748 non-null   object
 16  TP_DEPENDENCIA_ADM_ESC  225748 non-null   float64
 17  TP_LOCALIZACAO_ESC      225748 non-null   float64
 18  TP_SIT_FUNC_ESC         225748 non-null   float64
 19  CO_MUNICIPIO_PROVA      1048575 non-null  int64
 20  NO_MUNICIPIO_PROVA      1048575 non-null  object
 21  CO_UF_PROVA             1048575 non-null  int64
 22  SG_UF_PROVA             1048575 non-null  object
dtypes: float64(6), int64(12), object(5)
memory usage: 184.0+ MB

In [ ]:
list(df.columns)
# listando as colunas - de forma organizada

['NU_INSCRICAO',
 'NU_ANO',
 'TP_FAIXA_ETARIA',
 'TP_SEXO',
 'TP_ESTADO_CIVIL',
 'TP_COR_RACA',
 'TP_NACIONALIDADE',
 'TP_ST_CONCLUSAO',
 'TP_ANO_CONCLUIU',
 'TP_ESCOLA',
 'TP_ENSINO',
 'IN_TREINEIRO',
 'CO_MUNICIPIO_ESC',
 'NO_MUNICIPIO_ESC',
 'CO_UF_ESC',
 'SG_UF_ESC',
 'TP_DEPENDENCIA_ADM_ESC',
 'TP_LOCALIZACAO_ESC',
 'TP_SIT_FUNC_ESC',
 'CO_MUNICIPIO_PROVA',
 'NO_MUNICIPIO_PROVA',
 'CO_UF_PROVA',
 'SG_UF_PROVA']

In [ ]:
# Filtrar apenas os registros de Roraima (SG_UF_PROVA == 'RR')
df_limpo = df[df['SG_UF_PROVA'] == 'RR']

In [ ]:
df_limpo['SG_UF_PROVA'].value_counts()

SG_UF_PROVA
RR    2849
Name: count, dtype: int64

In [ ]:
# lista das colunas que vão ficar, as demais vão ser dropadas (mesmas colunas de 2024)
# em 2024 fiz dic de colunas para remover, aqui fiz o inverso (mais fácil) para não errar

colunas_desejadas = [
    'NU_INSCRICAO',
    'NU_ANO',
    'TP_FAIXA_ETARIA',
    'TP_SEXO',
    'TP_ESTADO_CIVIL',
    'TP_COR_RACA',
    'TP_NACIONALIDADE',
    'TP_ESCOLA',
    'TP_ENSINO',
    'IN_TREINEIRO',
    'NO_MUNICIPIO_PROVA',
    'SG_UF_PROVA',
    'TP_DEPENDENCIA_ADM_ESC',
    'TP_LOCALIZACAO_ESC'
]

df_limpo = df_limpo[colunas_desejadas]

In [ ]:
df_limpo.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
253,200004395365,2020,7,F,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
749,200005148853,2020,9,F,0,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1083,200006161469,2020,10,F,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1900,200005805354,2020,11,M,1,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN
1949,200005968413,2020,11,F,2,3,1,1,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# Dicionário de mapeamento
faixa_etaria_map = {
    1: "Menor de 17 anos",
    2: "17 anos",
    3: "18 anos",
    4: "19 anos",
    5: "20 anos",
    6: "21 anos",
    7: "22 anos",
    8: "23 anos",
    9: "24 anos",
    10: "25 anos",
    11: "Entre 26 e 30 anos",
    12: "Entre 31 e 35 anos",
    13: "Entre 36 e 40 anos",
    14: "Entre 41 e 45 anos",
    15: "Entre 46 e 50 anos",
    16: "Entre 51 e 55 anos",
    17: "Entre 56 e 60 anos",
    18: "Entre 61 e 65 anos",
    19: "Entre 66 e 70 anos",
    20: "Maior de 70 anos"
}

# substituir categoria pela descrição
df_limpo['TP_FAIXA_ETARIA'] = df_limpo['TP_FAIXA_ETARIA'].map(faixa_etaria_map)

In [ ]:
# dic de mapeamento
mapeamento_estado_civil = {
    0: "Não informado",
    1: "Solteiro(a)",
    2: "Casado(a)/Mora com companheiro(a)",
    3: "Divorciado(a)/Desquitado(a)/Separado(a)",
    4: "Viúvo(a)"
}


df_limpo['TP_ESTADO_CIVIL'] = df_limpo['TP_ESTADO_CIVIL'].map(mapeamento_estado_civil)

In [ ]:
# dicionário de mapeamento
mapeamento_cor = {
    0: "Não declarado",
    1: "Branca",
    2: "Preta",
    3: "Parda",
    4: "Amarela",
    5: "Indígena",
    6: "Não dispõe da informação"
}

# substituição
df_limpo['TP_COR_RACA'] = df_limpo['TP_COR_RACA'].map(mapeamento_cor)

df_limpo['TP_COR_RACA'].value_counts()

TP_COR_RACA
Parda            1927
Branca            480
Preta             233
Indígena          112
Não declarado      66
Amarela            31
Name: count, dtype: int64

In [ ]:
# dicionário de mapeamento
mapeamento_nacionalidade = {
    0: "Não informado",
    1: "Brasileiro(a)",
    2: "Brasileiro(a) Naturalizado(a)",
    3: "Estrangeiro(a)",
    4: "Brasileiro(a) Nato(a), nascido(a) no exterior"
}

# substituição
df_limpo['TP_NACIONALIDADE'] = df_limpo['TP_NACIONALIDADE'].map(mapeamento_nacionalidade)

In [ ]:
# dicionário de mapeamento
mapeamento_escola = {
    1: 'Não Respondeu',
    2: 'Pública',
    3: 'Privada'
}

# Substituir os valores numéricos pelos textos
df_limpo['TP_ESCOLA'] = df_limpo['TP_ESCOLA'].map(mapeamento_escola)

In [ ]:
df_limpo.head(10)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
253,200004395365,2020,22 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
749,200005148853,2020,24 anos,F,Não informado,Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
1083,200006161469,2020,25 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
1900,200005805354,2020,Entre 26 e 30 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
1949,200005968413,2020,Entre 26 e 30 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
3260,200001549389,2020,18 anos,F,Solteiro(a),Indígena,Brasileiro(a),Pública,1.0,0,Boa Vista,RR,2.0,1.0
3295,200006624801,2020,Entre 26 e 30 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,São João da Baliza,RR,NaN,NaN
3939,200005144676,2020,22 anos,F,Solteiro(a),Não declarado,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
4493,200003899122,2020,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN
4768,200006700027,2020,Entre 61 e 65 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,0,Boa Vista,RR,NaN,NaN

In [ ]:
# mapeamento TP_ENSINO
mapeamento_ensino = {
    1: "Ensino Regular",
    2: "Educação Especial - Modalidade Substitutiva"
}

df_limpo['TP_ENSINO'] = df_limpo['TP_ENSINO'].map(mapeamento_ensino)



# mapeamento IN_TREINEIRO
mapeamento_treineiro = {
    1: "Sim",
    0: "Não"
}

df_limpo['IN_TREINEIRO'] = df_limpo['IN_TREINEIRO'].map(mapeamento_treineiro)

In [ ]:
mapa_localizacao = {
    1: 'Urbana',
    2: 'Rural'
}

df_limpo['TP_LOCALIZACAO_ESC'] = df_limpo['TP_LOCALIZACAO_ESC'].map(mapa_localizacao)

In [ ]:
mapeamento_dependencia = {
    1: 'Federal',
    2: 'Estadual',
    3: 'Municipal',
    4: 'Privada'
}

df_limpo['TP_DEPENDENCIA_ADM_ESC'] = df_limpo['TP_DEPENDENCIA_ADM_ESC'].map(mapeamento_dependencia)

In [ ]:
df_limpo.head(15)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC
253,200004395365,2020,22 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
749,200005148853,2020,24 anos,F,Não informado,Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1083,200006161469,2020,25 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1900,200005805354,2020,Entre 26 e 30 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1949,200005968413,2020,Entre 26 e 30 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
3260,200001549389,2020,18 anos,F,Solteiro(a),Indígena,Brasileiro(a),Pública,Ensino Regular,Não,Boa Vista,RR,Estadual,Urbana
3295,200006624801,2020,Entre 26 e 30 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,São João da Baliza,RR,NaN,NaN
3939,200005144676,2020,22 anos,F,Solteiro(a),Não declarado,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
4493,200003899122,2020,18 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
4768,200006700027,2020,Entre 61 e 65 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
5189,200004191733,2020,19 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
5314,200005950838,2020,17 anos,M,Solteiro(a),Branca,Brasileiro(a),Pública,Ensino Regular,Não,Boa Vista,RR,Estadual,Urbana
5710,200004887669,2020,Menor de 17 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Sim,Boa Vista,RR,NaN,NaN
5924,200004292733,2020,21 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
6757,200006134766,2020,17 anos,F,Solteiro(a),Parda,Brasileiro(a),Pública,Ensino Regular,Não,Boa Vista,RR,NaN,NaN

In [ ]:
df_limpo.shape
# (linhas, colunas)

(2849, 14)

In [ ]:
# Dicionário de renomeação
novos_nomes = {
    'NU_INSCRICAO': 'inscricao',
    'NU_ANO': 'ano',
    'TP_FAIXA_ETARIA': 'faixa_etaria',
    'TP_SEXO': 'sexo',
    'TP_ESTADO_CIVIL': 'estado_civil',
    'TP_COR_RACA': 'cor_raca',
    'TP_NACIONALIDADE': 'nacionalidade',
    'TP_ESCOLA': 'tipo_escola',
    'TP_ENSINO': 'tipo_ensino',
    'IN_TREINEIRO': 'treineiro',
    'NO_MUNICIPIO_PROVA': 'municipio_prova',
    'SG_UF_PROVA': 'uf_prova',
    'TP_DEPENDENCIA_ADM_ESC': 'dependencia_adm_escola',
    'TP_LOCALIZACAO_ESC': 'localizacao_escola'
}

# nova variavel para novo dataset
# df → df_limpo → df_limpo_rr
df_limpo_rr = df_limpo.rename(columns=novos_nomes)

# ver as novas colunas
df_limpo_rr.columns

Index(['inscricao', 'ano', 'faixa_etaria', 'sexo', 'estado_civil', 'cor_raca',
       'nacionalidade', 'tipo_escola', 'tipo_ensino', 'treineiro',
       'municipio_prova', 'uf_prova', 'dependencia_adm_escola',
       'localizacao_escola'],
      dtype='object')

In [ ]:
df_limpo_rr.head()

,inscricao,ano,faixa_etaria,sexo,estado_civil,cor_raca,nacionalidade,tipo_escola,tipo_ensino,treineiro,municipio_prova,uf_prova,dependencia_adm_escola,localizacao_escola
253,200004395365,2020,22 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
749,200005148853,2020,24 anos,F,Não informado,Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1083,200006161469,2020,25 anos,F,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1900,200005805354,2020,Entre 26 e 30 anos,M,Solteiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN
1949,200005968413,2020,Entre 26 e 30 anos,F,Casado(a)/Mora com companheiro(a),Parda,Brasileiro(a),Não Respondeu,NaN,Não,Boa Vista,RR,NaN,NaN

In [ ]:
pasta_destino = '/content/drive/MyDrive/Projeto Final - DADOS_3_10/3. Bases de Dados Limpas'

# nome do arquivo .csv lá na pasta destino
arquivo_destino = pasta_destino + '/enem2020_rr_limpo.csv'

# df_limpo_rr vai ser salvo em .cvs
df_limpo_rr.to_csv(arquivo_destino, index=False, sep=';', encoding='utf-8')

print(f"Arquivo salvo em: {arquivo_destino}")

Arquivo salvo em: /content/drive/MyDrive/Projeto Final - DADOS_3_10/3. Bases de Dados Limpas/enem2020_rr_limpo.csv